---
ID: "914fd985-18a8-4e24-a55c-4ef8717eb462"
Parent: "a06a0893-c60a-4565-9e92-b1f097c2b4b3"
Template: "a06a0893-c60a-4565-9e92-b1f097c2b4b3"
Path: /sitecore/templates/Feature/Content/Datasources/Comments Module/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{47CF84B9-AEB6-48CE-894B-9380E4DDEF60}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230419T125459Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "273358b7-f056-49db-ae63-3497ada00e4c"
    - ID: "b1bf2ac6-066c-446a-a5f1-371884e4f41d"
      Hint: Title
      Value: $name
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230419T132928Z
