---
ID: "0bcd826a-1220-4bb7-a95d-e73f104d274c"
Parent: "067265fc-edf5-413e-8ebe-e476cafb540f"
Template: "067265fc-edf5-413e-8ebe-e476cafb540f"
Path: /sitecore/templates/Foundation/AI/Datasources/Template Setting/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{C74BFF6E-2E32-4FEF-927B-31A2C3D0D9FB}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231012T171525Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\tzoxyd3zg1
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\tzoxyd3zg1
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "52a01d81-e095-48ab-9106-e1d9a4c71701"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\tzoxyd3zg1
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231012T171541Z
