---
ID: "16c772c3-a3ba-4206-9f5a-639e9dd134e2"
Parent: "78af59f1-be34-472a-9df1-c2edba74733c"
Template: "78af59f1-be34-472a-9df1-c2edba74733c"
Path: /sitecore/templates/Feature/Products/Datasources/Cart/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230108T185313Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "edf9911c-1014-469b-8420-b8d67fba29e6"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230108T192427Z
    - ID: "f125bdde-9190-4743-ac46-b1ee8eaaad19"
      Hint: Title
      Value: $name
