---
ID: "c47f745a-cff2-4e3f-8557-173e3b4e8a05"
Parent: "65acf341-8df8-47d3-9923-8496a54605ae"
Template: "65acf341-8df8-47d3-9923-8496a54605ae"
Path: /sitecore/templates/Feature/Products/Folders/Global Profile Personal Preferences/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{FADECE34-B1D1-4E0E-B539-E46FDF6408F7}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230313T192342Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "69ad0f68-6e73-48f6-b787-291b584c30f7"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230313T192357Z
