---
ID: "bb1caf38-71c5-4b84-a837-53998b251714"
Parent: "17cfdb4e-e056-46e9-aff3-14084358293d"
Template: "3aea335c-d06d-45b1-841a-cbc8d2d1ce40"
Path: /sitecore/system/Settings/Foundation/AI/AI Headless Site Setup/Add AI Settings
SharedFields:
- ID: "52c91c75-6698-4701-a8a2-242ace59a8d6"
  Hint: Location
  Value: "{9AF6CE61-4FC5-43EE-9014-03E9D9C9C3DF}"
- ID: "7868e6bc-525c-4fce-ab8a-77da3e09b171"
  Hint: Name
  Value: AI
- ID: "e62c28f0-9d3b-46e2-8bec-a5e120542499"
  Hint: Template
  Value: "{25533CBD-7D5D-4873-BD77-C8F56E1124C7}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221212T083816Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8768f2e9-46a7-450e-b460-448111439871"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\tzoxyd3zg1
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231012T171625Z
