---
ID: "42575c44-1eaa-400c-9522-09abd096f2ce"
Parent: "25533cbd-7d5d-4873-bd77-c8f56e1124c7"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Foundation/AI/Datasources/Settings/AI Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231012T170355Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\tzoxyd3zg1
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\tzoxyd3zg1
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "96bc9c32-6688-4b3f-bfb2-ad15a2681e07"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\tzoxyd3zg1
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231012T170355Z
