---
ID: "b59dd569-5658-4c85-b8f5-ee43b53edcdb"
Parent: "ffed6e39-4b54-4a5d-bdf9-37824d4a825b"
Template: "ffed6e39-4b54-4a5d-bdf9-37824d4a825b"
Path: /sitecore/templates/Feature/Products/Rendering Parameters/Wishlist/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221201T141403Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "06a43b0a-3eb0-4fc0-9731-3732ebe46c62"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230801T111211Z
