---
ID: "e8719ca5-2164-46c0-91c1-b6881329b7ab"
Parent: "3f8a6a5d-7b1a-4566-8cd4-0a50f3030bd8"
Template: "3f8a6a5d-7b1a-4566-8cd4-0a50f3030bd8"
Path: /sitecore/templates/Foundation/Experience Accelerator/Multisite/Content/Page/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{3F8A6A5D-7B1A-4566-8CD4-0A50F3030BD8}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{BCFC7537-EFF4-434C-96F5-BF4F55FD175B}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160628T133845Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f465f942-8cd3-4cf3-8043-d64405b16197"
