---
ID: "e3ead73d-0740-4aba-bb48-7d866d9ee41e"
Parent: "47cf84b9-aeb6-48ce-894b-9380e4ddef60"
Template: "47cf84b9-aeb6-48ce-894b-9380e4ddef60"
Path: /sitecore/templates/Feature/Content/Datasources/Elements/Comment Element/__Standard Values
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{36C9B4FD-2F35-4E95-BCE6-ADE4254763A2}"
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{36C9B4FD-2F35-4E95-BCE6-ADE4254763A2}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230419T121323Z
    - ID: "2ffedbb1-6457-45fc-a2c1-0beff0e16a5f"
      Hint: ReviewDate
      Value: $now
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c9291e8b-2e79-43f9-ae05-f7b6878f3ced"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230420T160355Z
