---
ID: "2232c28d-c4e7-4bd4-a5cf-78da4fd2226c"
Parent: "1b6bc7d0-6a9e-4ad7-b00b-9b2fa24386fb"
Template: "3aea335c-d06d-45b1-841a-cbc8d2d1ce40"
Path: /sitecore/system/Settings/Feature/Products/Products Site Setup/Add Products Settings
SharedFields:
- ID: "52c91c75-6698-4701-a8a2-242ace59a8d6"
  Hint: Location
  Value: "{9AF6CE61-4FC5-43EE-9014-03E9D9C9C3DF}"
- ID: "7868e6bc-525c-4fce-ab8a-77da3e09b171"
  Hint: Name
  Value: Products
- ID: "e62c28f0-9d3b-46e2-8bec-a5e120542499"
  Hint: Template
  Value: "{473D4A8A-5FBF-461C-A52C-E01316DA7E1D}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221212T083816Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b219ebf5-2561-45a7-b116-72c3c6d8211c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221226T144000Z
